using Qdrant.Client;
using Qdrant.Client.Grpc;

namespace studio_api.Data;

public static class QdrantSetup
{
    public static async Task EnsureMomentsCollectionExists(QdrantClient client)
    {
        var collections = await client.ListCollectionsAsync();
        if (!collections.Contains("moments"))
            await client.CreateCollectionAsync("moments", new VectorParams
            {
                Size = 384, // as generated by all-MiniLM-L6-v2
                Distance = Distance.Cosine
            });
    }
}